<a href="https://colab.research.google.com/github/arpitsharma27/PythonPractice/blob/main/UniversityOf_Michigan_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The below content is from Coursera's course 

"**Understanding and Visualizing Data with Python**" week 2. 

This course is provided by **University Of Washington**.  

In [1]:
import numpy as np

In [25]:
### Create a 3x1 numpy array
a = np.array([1,2,3])

### Print object type
type_a=type(a)
print('type of array a --' + str(type_a))

### Print shape
shape_a=a.shape
print('Shape of array a -- ' + str(shape_a))

### Print some values in a
print('Some values of array a -- ' + str(a[0]), str(a[1]), str(a[2]))

### Create a 2x2 numpy array
b = np.array([[1,2],[3,4]])

### Print shape
print(b.shape)
print('shape of array b --' + str(b.shape))

## Print some values in b
print(b[0,0], b[0,1], b[1,1])
print('Some values in array b --' + str(b[0,0]) + str(b[0,1]) + str(b[1,1])  )

### Create a 3x2 numpy array
c = np.array([[1,2],[3,4],[5,6]])

### Print shape
print(c.shape)

### Print some values in c
print(c[0,1], c[1,0], c[2,0], c[2,1])

type of array a --<class 'numpy.ndarray'>
Shape of array a -- (3,)
Some values of array a -- 1 2 3
(2, 2)
shape of array b --(2, 2)
1 2 4
Some values in array b --124
(3, 2)
2 3 5 6


In [26]:
### 2x3 zero array 
d = np.zeros((2,3))

print(d)

### 4x2 array of ones
e = np.ones((4,2))

print(e)

### 2x2 constant array
f = np.full((2,2), 9)

print(f)

### 3x3 random array
g = np.random.random((3,3))

print(g)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[0.19002407 0.07967394 0.95551707]
 [0.7177553  0.37711794 0.28908582]
 [0.14566239 0.3591406  0.54178139]]


In [39]:
#Practice
p1=np.zeros((4,3))
print(p1)
print("")
p2=np.zeros_like(p1)
print(p2)
print()
p3=np.random.randint((3,3))
print(p3)
print()
p4=np.full((3,3),5)
print(p4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[2 0]

[[5 5 5]
 [5 5 5]
 [5 5 5]]


**Array Indexing**

In [58]:
### Create 3x4 array
h = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])

print(h)

### Slice array to make a 2x2 sub-array
i = h[:2, 1:3]

print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [59]:
print(h[0,1])

### Modify the slice
i[0,0] = 1738

### Print to show how modifying the slice also changes the base object
print(h[0,1])

2
1738


In [57]:
p1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(p1)
only_5=p1[1:2,1:2]
print(only_5)
print("")
p2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(p2)
only_1=p2[0:4,0:1]
print(only_1)
print()
only_2=p2[:,1:2] ## You dont have to specify any number before/after a colon if you want all members.
print(only_2)
print()
all_234=p2[:,1:4]
print(all_234)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5]]

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1]
 [1]
 [1]]

[[2]
 [2]
 [2]]

[[2 3 4]
 [2 3 4]
 [2 3 4]]


**Datatypes in Arrays**