<a href="https://colab.research.google.com/github/arpitsharma27/PythonPractice/blob/main/UniversityOf_Michigan_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The below content is from Coursera's course 

"**Understanding and Visualizing Data with Python**" week 2. 

This course is provided by **University Of Washington**.  

In [3]:
import numpy as np

In [4]:
### Create a 3x1 numpy array
a = np.array([1,2,3])

### Print object type
type_a=type(a)
print('type of array a --' + str(type_a))

### Print shape
shape_a=a.shape
print('Shape of array a -- ' + str(shape_a))

### Print some values in a
print('Some values of array a -- ' + str(a[0]), str(a[1]), str(a[2]))

### Create a 2x2 numpy array
b = np.array([[1,2],[3,4]])

### Print shape
print(b.shape)
print('shape of array b --' + str(b.shape))

## Print some values in b
print(b[0,0], b[0,1], b[1,1])
print('Some values in array b --' + str(b[0,0]) + str(b[0,1]) + str(b[1,1])  )

### Create a 3x2 numpy array
c = np.array([[1,2],[3,4],[5,6]])

### Print shape
print(c.shape)

### Print some values in c
print(c[0,1], c[1,0], c[2,0], c[2,1])

type of array a --<class 'numpy.ndarray'>
Shape of array a -- (3,)
Some values of array a -- 1 2 3
(2, 2)
shape of array b --(2, 2)
1 2 4
Some values in array b --124
(3, 2)
2 3 5 6


In [5]:
### 2x3 zero array 
d = np.zeros((2,3))

print(d)

### 4x2 array of ones
e = np.ones((4,2))

print(e)

### 2x2 constant array
f = np.full((2,2), 9)

print(f)

### 3x3 random array
g = np.random.random((3,3))

print(g)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[0.7758397  0.28993818 0.07982561]
 [0.73918093 0.71149522 0.82272168]
 [0.95902833 0.10874694 0.25653385]]


In [6]:
#Practice
p1=np.zeros((4,3))
print(p1)
print("")
p2=np.zeros_like(p1)
print(p2)
print()
p3=np.random.randint((3,3))
print(p3)
print()
p4=np.full((3,3),5)
print(p4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1 2]

[[5 5 5]
 [5 5 5]
 [5 5 5]]


**Array Indexing**

In [7]:
### Create 3x4 array
h = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])

print(h)

### Slice array to make a 2x2 sub-array
i = h[:2, 1:3]

print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [8]:
print(h[0,1])

### Modify the slice
i[0,0] = 1738

### Print to show how modifying the slice also changes the base object
print(h[0,1])

2
1738


In [9]:
p1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(p1)
only_5=p1[1:2,1:2]
print(only_5)
print("")
p2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(p2)
only_1=p2[0:4,0:1]
print(only_1)
print()
only_2=p2[:,1:2] ## You dont have to specify any number before/after a colon if you want all members.
print(only_2)
print()
all_234=p2[:,1:4]
print(all_234)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5]]

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1]
 [1]
 [1]]

[[2]
 [2]
 [2]]

[[2 3 4]
 [2 3 4]
 [2 3 4]]


**Datatypes in Arrays**

Datatypes in arrays is different than type of array.

In [11]:
##Integer
j=np.array([1,2])
print(j.dtype)
print(type(j))

int64
<class 'numpy.ndarray'>


In [12]:
#Float
f=np.array([1.0, 2.4])
print(f.dtype)
print(type(f))

float64
<class 'numpy.ndarray'>


In [14]:
#Force Data Type
fdtype=np.array([1.0,2.0],dtype=np.int64)
sdtype=np.array([1.0,2.0],dtype='S')
print(fdtype.dtype)
print(sdtype.dtype)
print(type(fdtype))

int64
|S3
<class 'numpy.ndarray'>


**ARRAY MATH**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [28]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [30]:
print(x)
print()
print(y)
print()
print(x+y)
print()
print(x*y)
print()
print(x**y)

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 5. 12.]
 [21. 32.]]

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [29]:
print(x)
print()
print(y)
print()
print(np.add(x,y))
print()
print(np.subtract(x,y))
print()
print(np.multiply(x,y))
print()
print(np.power(x,y))

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [36]:
print(x)
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

[[1. 2.]
 [3. 4.]]
2.5
[2. 3.]
[1.5 3.5]


In [37]:
mean_all=np.mean(x)
print(mean_all)
print(type(mean_all))

2.5
<class 'numpy.float64'>


In [39]:
mean_rows=np.mean(x,axis=1)
print(mean_rows)
print(type(mean_rows))

[1.5 3.5]
<class 'numpy.ndarray'>


In [40]:
mean_cols=np.mean(x,axis=0)
print(mean_cols)
print(type(mean_cols))

[2. 3.]
<class 'numpy.ndarray'>


**SciPy**

Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

SciPy.Stats is just one of the sub-libraries.

**SciPy.Stats**

The SciPy.Stats module contains a large number of probability distributions as well as a growing library of statistical functions such as:


*   Continuous and Discrete Distributions(i.e. Normal, Uniform, Binomial, etc.)
*   Descriptive Statistics
*   Statistical Tests(i.e. T-Test)








In [41]:
from scipy import stats
import numpy as np